package pl.pcz.wimii.top.jadlodajnia.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import pl.pcz.wimii.top.jadlodajnia.db.Dish;
import pl.pcz.wimii.top.jadlodajnia.db.Product;
import pl.pcz.wimii.top.jadlodajnia.db.DishProduct;

import pl.pcz.wimii.top.jadlodajnia.db.DishDao;
import pl.pcz.wimii.top.jadlodajnia.db.ProductDao;
import pl.pcz.wimii.top.jadlodajnia.db.DishProductDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dishDaoConfig;
    private final DaoConfig productDaoConfig;
    private final DaoConfig dishProductDaoConfig;

    private final DishDao dishDao;
    private final ProductDao productDao;
    private final DishProductDao dishProductDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dishDaoConfig = daoConfigMap.get(DishDao.class).clone();
        dishDaoConfig.initIdentityScope(type);

        productDaoConfig = daoConfigMap.get(ProductDao.class).clone();
        productDaoConfig.initIdentityScope(type);

        dishProductDaoConfig = daoConfigMap.get(DishProductDao.class).clone();
        dishProductDaoConfig.initIdentityScope(type);

        dishDao = new DishDao(dishDaoConfig, this);
        productDao = new ProductDao(productDaoConfig, this);
        dishProductDao = new DishProductDao(dishProductDaoConfig, this);

        registerDao(Dish.class, dishDao);
        registerDao(Product.class, productDao);
        registerDao(DishProduct.class, dishProductDao);
    }
    
    public void clear() {
        dishDaoConfig.getIdentityScope().clear();
        productDaoConfig.getIdentityScope().clear();
        dishProductDaoConfig.getIdentityScope().clear();
    }

    public DishDao getDishDao() {
        return dishDao;
    }

    public ProductDao getProductDao() {
        return productDao;
    }

    public DishProductDao getDishProductDao() {
        return dishProductDao;
    }

}
